version: "3"

services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  # postgresdb: 
  #   build: 
  #     context: ./docker/postgres
  #     dockerfile: Dockerfile
  #   environment: 
  #    # - POSTGRES_PASSWORD = admin
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  #     POSTGRES_USER: ${POSTGRES_USER:-admin}
  #     POSTGRES_DB: ${POSTGRES_DB:-photogram}
  #   volumes:
  #     - ./docker/posgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"

  # web:
  #   build: 
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #   depends_on: 
  #     - postgresdb
  #   ports:
  #     - "8000:8000"

      

